///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VENUS_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VENUS_DemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c117cbf5-fca2-4e90-a8e0-fda4b49ad90a")]
    public partial class VENUS_DemoRepository : RepoGenBaseFolder
    {
        static VENUS_DemoRepository instance = new VENUS_DemoRepository();
        VENUS_DemoRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        VENUS_DemoRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the VENUS_DemoRepository element repository.
        /// </summary>
        [RepositoryFolder("c117cbf5-fca2-4e90-a8e0-fda4b49ad90a")]
        public static VENUS_DemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VENUS_DemoRepository() 
            : base("VENUS_DemoRepository", "/", null, 0, false, "c117cbf5-fca2-4e90-a8e0-fda4b49ad90a", ".\\RepositoryImages\\VENUS_DemoRepositoryc117cbf5.rximgres")
        {
            _applicationundertest = new VENUS_DemoRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new VENUS_DemoRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c117cbf5-fca2-4e90-a8e0-fda4b49ad90a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("83318af3-3b60-4968-a197-61e3217d9f1d")]
        public virtual VENUS_DemoRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("21839bad-e601-4e09-9169-9fe21724bd6e")]
        public virtual VENUS_DemoRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class VENUS_DemoRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("83318af3-3b60-4968-a197-61e3217d9f1d")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _musicInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _malerbInfo;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _countInfo;
            RepoItemInfo _clearInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "83318af3-3b60-4968-a197-61e3217d9f1d", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", 30000, null, "642886d5-02ce-4ef9-9f25-9c43b78b4a67");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", 30000, null, "76a38469-c705-40d3-ac1f-3bd77e4ba713");
                _musicInfo = new RepoItemInfo(this, "Music", ".//select[#'Category']/option[@value='Music']", 30000, null, "d09107bc-f7c5-4d99-af03-e047fb2c0ae2");
                _movieInfo = new RepoItemInfo(this, "Movie", ".//select[#'Category']/option[@value='Movie']", 30000, null, "a8ba2d47-8d6a-4ae9-b974-c6aefc2436c0");
                _malerbInfo = new RepoItemInfo(this, "MaleRb", ".//td[#'gender']//input[@name='Gender' and @type='radio' and @value='male']", 30000, null, "a3cbaa6a-8ed9-4f7a-a6fc-440746857dc3");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", 30000, null, "6944e411-6580-4b0f-882a-b98fc3f49afb");
                _countInfo = new RepoItemInfo(this, "Count", ".//td[#'count']", 30000, null, "8817c67f-1bdb-4cec-9194-8e92ce191cef");
                _clearInfo = new RepoItemInfo(this, "Clear", ".//input[#'Clear']", 30000, null, "cba3267f-374a-41ac-8883-af24d42f49b9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("83318af3-3b60-4968-a197-61e3217d9f1d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("83318af3-3b60-4968-a197-61e3217d9f1d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("642886d5-02ce-4ef9-9f25-9c43b78b4a67")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("642886d5-02ce-4ef9-9f25-9c43b78b4a67")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("76a38469-c705-40d3-ac1f-3bd77e4ba713")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("76a38469-c705-40d3-ac1f-3bd77e4ba713")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("d09107bc-f7c5-4d99-af03-e047fb2c0ae2")]
            public virtual Ranorex.OptionTag Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("d09107bc-f7c5-4d99-af03-e047fb2c0ae2")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("a8ba2d47-8d6a-4ae9-b974-c6aefc2436c0")]
            public virtual Ranorex.OptionTag Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("a8ba2d47-8d6a-4ae9-b974-c6aefc2436c0")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The MaleRb item.
            /// </summary>
            [RepositoryItem("a3cbaa6a-8ed9-4f7a-a6fc-440746857dc3")]
            public virtual Ranorex.InputTag MaleRb
            {
                get
                {
                    return _malerbInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The MaleRb item info.
            /// </summary>
            [RepositoryItemInfo("a3cbaa6a-8ed9-4f7a-a6fc-440746857dc3")]
            public virtual RepoItemInfo MaleRbInfo
            {
                get
                {
                    return _malerbInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("6944e411-6580-4b0f-882a-b98fc3f49afb")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("6944e411-6580-4b0f-882a-b98fc3f49afb")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Count item.
            /// </summary>
            [RepositoryItem("8817c67f-1bdb-4cec-9194-8e92ce191cef")]
            public virtual Ranorex.TdTag Count
            {
                get
                {
                    return _countInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Count item info.
            /// </summary>
            [RepositoryItemInfo("8817c67f-1bdb-4cec-9194-8e92ce191cef")]
            public virtual RepoItemInfo CountInfo
            {
                get
                {
                    return _countInfo;
                }
            }

            /// <summary>
            /// The Clear item.
            /// </summary>
            [RepositoryItem("cba3267f-374a-41ac-8883-af24d42f49b9")]
            public virtual Ranorex.InputTag Clear
            {
                get
                {
                    return _clearInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Clear item info.
            /// </summary>
            [RepositoryItemInfo("cba3267f-374a-41ac-8883-af24d42f49b9")]
            public virtual RepoItemInfo ClearInfo
            {
                get
                {
                    return _clearInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("21839bad-e601-4e09-9169-9fe21724bd6e")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _startInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "21839bad-e601-4e09-9169-9fe21724bd6e", "")
            {
                _startInfo = new RepoItemInfo(this, "Start", "?/?/button[@accessiblename='Start']", 30000, null, "08d173b0-1e73-489a-a7d9-c7cbc1b266d4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("21839bad-e601-4e09-9169-9fe21724bd6e")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("21839bad-e601-4e09-9169-9fe21724bd6e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Start item.
            /// </summary>
            [RepositoryItem("08d173b0-1e73-489a-a7d9-c7cbc1b266d4")]
            public virtual Ranorex.Button Start
            {
                get
                {
                    return _startInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Start item info.
            /// </summary>
            [RepositoryItemInfo("08d173b0-1e73-489a-a7d9-c7cbc1b266d4")]
            public virtual RepoItemInfo StartInfo
            {
                get
                {
                    return _startInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
